### ISSUE TITLE
Not working with Lithuanian language locale

### ISSUE THREAD

**Issue by gedpal** [PsCustomObject/PsCustomObject-Message-Tracker#4]
![Capture](https://user-images.githubusercontent.com/45728964/69319022-0b4c9100-0c47-11ea-9e98-ee54bdef1687.JPG)

**Comment by gedpal** [comment]
Sasilik commented and it actually solves a problem with non English locales:
I had the same problem and I replaced .Text with .Value in rows 564 and 570 $startDate = $date_start.Text -> $startDate = $date_start.Value
$endDate = $date_end.Text -> $endDate = $date_end.Value
That solved the problem for me.

**Comment by PsCustomObject** [comment]
Yes this is a known issue that will be fixed when version 2.0.0 will be released

**Comment by NazZaR** [comment]
> Yes this is a known issue that will be fixed when version 2.0.0 will be released

Any chance on release date? :)

**Comment by PsCustomObject** [comment]
Ah ah that's a good question @NazZaR I have to admit I kind of neglected work on this in favor of other stuff (working on a WinSCP drop-in for PowerShell and my IT-ToolBox module) as unfortunately I am not working a lot on messaging stuff as of lately.

But given I see there is still demand for the tool and people using it I will resume work on it, Version 2.0.0 is more a rewrite from scratch as there was a lot of stuff I did not like in this version. 

I will try to target, but don't take for granted, an early January release. 

Feel free to follow the project so you can see when I commit something to the repository and you can test drive the new version, help on testing is always more than welcome!

**Comment by NazZaR** [comment]
> Ah ah that's a good question @NazZaR I have to admit I kind of neglected work on this in favor of other stuff (working on a WinSCP drop-in for PowerShell and my IT-ToolBox module) as unfortunately I am not working a lot on messaging stuff as of lately.
> 
> But given I see there is still demand for the tool and people using it I will resume work on it, Version 2.0.0 is more a rewrite from scratch as there was a lot of stuff I did not like in this version.
> 
> I will try to target, but don't take for granted, an early January release.
> 
> Feel free to follow the project so you can see when I commit something to the repository and you can test drive the new version, help on testing is always more than welcome!

Alright, thank you!
